#!/bin/bash

echo ">"
echo "Redireciona a saída padrão do comando para um arquivo, sobrescrevendo o arquivo"
echo "cat help_red.sh > arquivo.txt"
echo ">>"
echo "Redireciona a saída padrão do comando para um arquivo, adicionando-o no final da linha de um arquivo"
echo "grep echo help_red.sh | wc -l >> arquivo.txt"
echo "2>"
echo "Redireciona a saída padrão de erros de um comando para um arquivo, sobrescrevendo o arquivo em questão"
echo "ls -l /home/aluno/vasco 2> melhor_time.txt"
echo "2>>"
echo "Redireciona a saída padrão de erros de um comando para um arquivo, adicionando-o no final da linha de um arquivo"
echo "ls -l /home/aluno/flamengo 2>> pior_time.txt"
echo "&>"
echo "Redireciona todas as saídas  do comando para um arquivo, sobrescrevendo o arquivo"
echo "fdisk -l /dev/sda &> arquivo.txt"
echo "&>>"
echo "Redireciona todas as saídas  do comando para um arquivo, adicionando no final da linha de um arquivo"
echo "fdisk -l /dev/sdb &>> arquivo.txt"
echo "<"
echo "Redireciona  um arquivo para entrada padrão de um comando"
echo "grep palavra < arquivo.txt"
echo "<<"
echo "Redireciona a entrada padrão do comando para o documento escrito no bash"
echo "cat <<END"
echo "<<<"
echo "Redireciona a entrada padrão do comando para a string escrita no bash"
echo 'grep p <<< "palavra"' 
echo "|"
echo "Conecta um comando a outro comando"
echo 'cat arquivo.txt | grep p <<< "palavra"' 
